name: Nightly build to test
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Build project
        run: |
          npm install
          npm run build
          
          ## save latest version tag
          TAG_NAME=$(curl -sL https://api.github.com/repos/mynaparrot/plugNmeet-client/releases/latest | jq -r ".tag_name")
          echo $TAG_NAME > dist/version.txt
          
          mkdir -p tmp/client
          rsync -ar dist tmp/client/
          cd tmp
          zip -X -r client.zip client
      - name: Upload by ftp
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.PNM_FTP_HOST }}
          username: ${{ secrets.PNM_FTP_USER }}
          password: ${{ secrets.PNM_FTP_PASSWORD }}
          local-dir: "./tmp/"
          state-name: ".client-sync-state.json"
          exclude: |
            **/client/**
